version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/samples/*"
      - "/src/*"
      - "/test/*"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Microsoft.*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      "microsoft-packages":
        patterns:
          - "Microsoft.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
