name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      matrix:
        dotnet: ['10.0']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.2.0
      - uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: 10
      - name: build
        run: dotnet build
      - name: test Finbuckle.MultiTenant
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }}
        working-directory: ./test/Finbuckle.MultiTenant.Test
      - name: test Finbuckle.MultiTenant.AspNetCore
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }}
        working-directory: ./test/Finbuckle.MultiTenant.AspNetCore.Test
      - name: test Finbuckle.MultiTenant.EntityFrameworkCore
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }}
        working-directory: ./test/Finbuckle.MultiTenant.EntityFrameworkCore.Test
        
