name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        dotnet: ['10.0']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v6.2.0
      - uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          dotnet-version: 10
      - name: build
        run: dotnet build
      - name: test Finbuckle.MultiTenant
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }}
        working-directory: ./test/Finbuckle.MultiTenant.Test
      - name: test Finbuckle.MultiTenant.AspNetCore
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }}
        working-directory: ./test/Finbuckle.MultiTenant.AspNetCore.Test
      - name: test Finbuckle.MultiTenant.EntityFrameworkCore
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }}
        working-directory: ./test/Finbuckle.MultiTenant.EntityFrameworkCore.Test
        
