name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        dotnet: ['10.0']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10
      - name: build
        run: dotnet build
      - name: test Finbuckle.MultiTenant
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }}
        working-directory: ./test/Finbuckle.MultiTenant.Test
      - name: test Finbuckle.MultiTenant.AspNetCore
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }}
        working-directory: ./test/Finbuckle.MultiTenant.AspNetCore.Test
      - name: test Finbuckle.MultiTenant.EntityFrameworkCore
        run: dotnet test --no-build -v q -f net${{ matrix.dotnet }}
        working-directory: ./test/Finbuckle.MultiTenant.EntityFrameworkCore.Test
        
