name: MacOS (.NET 7.0)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  os-tests:
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: test Finbuckle.MultiTenant
        run: dotnet test -f net7.0
        working-directory: ./test/Finbuckle.MultiTenant.Test
      - name: test Finbuckle.MultiTenant.AspNetCore
        run: dotnet test -f net7.0
        working-directory: ./test/Finbuckle.MultiTenant.AspNetCore.Test
      - name: test Finbuckle.MultiTenant.EntityFrameworkCore
        run: dotnet test -f net7.0
        working-directory: ./test/Finbuckle.MultiTenant.EntityFrameworkCore.Test
